package me.parth.shoku.domain.model

import androidx.compose.ui.graphics.Color

/**
 * Represents a distinct type of food item with its nutritional information per standard unit.
 * Used for suggestions and potentially pre-filling data.
 *
 * @param id Unique identifier for the food item.
 * @param name Name of the food (e.g., "Milk", "Apple").
 * @param calories Calories per standard unit (e.g., per 100g, per 1 piece).
 * @param protein Protein per standard unit.
 * @param defaultUnit Default unit associated with these values (e.g., "g", "ml", "pc"). Optional.
 * @param frequency How often this item has been logged (for suggestion ranking).
 */
data class FoodItem(
    val id: Int = 0, // Auto-generated by Room
    val name: String,
    val calories: Double,
    val protein: Double,
    val defaultUnit: String? = null,
    val frequency: Int = 0
) 